using System.Xml.Serialization;
using OpenQA.Selenium;
using System.Linq;
using System.Collections.Generic;

namespace Gander.Library
{
    public enum InsertedKeySource
    {
        /// <summary>
        /// Inserted key can be found at the very end of URL (i.e. MVC insert /Controller/Action/{key})
        /// </summary>
        UrlEnd,
        /// <summary>
        /// Inserted key can be found in the URL by regular expression
        /// </summary>
        UrlRegex,
        /// <summary>
        /// Key is embedded in the page somewhere within a span element
        /// </summary>
        SpanId,
        /// <summary>
        /// Inserted key must be queried via @@IDENTITY or some such (not necessarily reliable)
        /// </summary>
        Query
    }

    /// <summary>
    /// Describes an interaction with an HTML form by navigating to it, setting one or more fields and then submitting
    /// </summary>
    public class Form : TestStep
    {
        private Field[] _fields;
        private Dictionary<string, Field> _fieldDictionary;

        /// <summary>
        /// URL containing the form to submit
        /// </summary>
        [XmlAttribute("url")]
        public string Url { get; set; }

        /// <summary>
        /// Enables Gander to find the form on a page by its action attribute of the HTML form element
        /// </summary>
        [XmlAttribute("action")]
        public string ElementAction { get; set; }

        /// <summary>
        /// Enables Gander to find the form on a page by the Id attribute of the HTML form element
        /// </summary>
        [XmlAttribute("id")]
        public string ElementId { get; set; }

        /// <summary>
        /// After a record is inserted, where can I find the key to the database record?
        /// </summary>
        public InsertedKeySource InsertedKeySource { get; set; } = InsertedKeySource.UrlEnd;

        /// <summary>
        /// Regex that parses the URL for the inserted key, or the element ID of the span containing the inserted key
        /// </summary>
        public string InsertedKeySelector { get; set; }

        /// <summary>
        /// Value generated by an insert
        /// </summary>
        [XmlIgnore]
        public object InsertedKey { get; set; }

        public Field[] Fields
        {
            get { return _fields; }
            set
            {
                _fields = value;
                _fieldDictionary = _fields.ToDictionary(item => item.ElementId);
            }
        }

        public Field this[string elementId]
        {
            get { return _fieldDictionary[elementId]; }
        }

        public class Field
        {
            [XmlAttribute("name")]
            public string ElementId { get; set; }
            
            public object Value { get; set; }
        }

        protected override void OnExecute(string role, IWebDriver driver, Application application, Environment environment)
        {
            driver.Url = this.Url;
            driver.Navigate();

            foreach (var field in Fields)
            {
                var element = driver.FindElement(By.Id(field.ElementId));
                element.SendKeys(field.Value.ToString());
            }

            var form = driver.FindElement(By.Id(this.ElementId));
            form.Submit();

            switch (InsertedKeySource)
            {
                case InsertedKeySource.UrlEnd:
                    InsertedKey = driver.Url.Split('/').Last();
                    break;
            }
        }
    }
}